import "./globals.css";
import "@fontsource/vazir";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="font-vazir">
      <body className="h-full md:flex md:items-center md:justify-center md:min-h-screen bg-[#1c262f]">
        {children}
      </body>
    </html>
  );
}
